name: Android Build Check Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: Setup Environment and build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate app bundle
        run: ./gradlew clean app:assembleDebug --stacktrace

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/*/*.apk